artifacts_dir: artifacts

data_ingestion:
    ingestion_dir: artifacts/data_ingestion
    cluster_db: rec-engine-db
    prod_collection: prodCollection
    category_collection: prodCategories 


vector_store:
    pc_index: products
    params: config/params.yml


inference_apis:
    cluster_db: rec-engine-db
    prod_collection: prodCollection
    pc_index: products